# Ansible inventory created from ['basic.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
  ipv6: true
box: ceos:4.28.1F
clab:
  env:
    INTFTYPE: et
  kind: ceos
hostname: clab-basic-R3
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.6/30
  ipv6: true
  linkindex: 2
  name: R3 -> R2
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.5/30
    ipv6: true
    node: R2
  type: p2p
loopback:
  ipv4: 10.0.0.3/32
  ipv6: 200:0:0:3::1/64
mgmt:
  ifname: Management0
  ipv4: 192.168.121.103
  mac: 08-4F-A9-00-00-03
