[general]
id = "sd1-ff00_0_111"
config_dir = "/share/conf"
reconnect_to_dispatcher = true

[trust_db]
connection = "/share/cache/sd1-ff00_0_111.trust.db"

[path_db]
connection = "/share/cache/sd1-ff00_0_111.path.db"

[sd]
address = "172.24.4.102:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "172.24.4.102:30455"

[features]

[api]
addr = "172.24.4.102:30955"

[log.console]
level = "debug"
