# Ansible inventory created from ['bgp.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65000
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65100
    ifindex: 1
    ipv4: 10.1.0.1
    name: l1
    type: ebgp
  - as: 65101
    ifindex: 2
    ipv4: 10.1.0.5
    name: l2
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.1
box: ceos:4.28.1F
clab:
  env:
    INTFTYPE: et
  kind: ceos
hostname: clab-basic-s1
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.2/30
  linkindex: 1
  name: s1 -> l1
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.1/30
    node: l1
  role: external
  type: p2p
- clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.6/30
  linkindex: 2
  name: s1 -> l2
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.5/30
    node: l2
  role: external
  type: p2p
loopback:
  ipv4: 10.0.0.1/32
mgmt:
  ifname: Management0
  ipv4: 192.168.121.101
  mac: 08-4F-A9-00-00-01
module:
- bgp
