# Ansible inventory created from ['bgp.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
box: python:3.9-alpine
clab:
  kind: linux
hostname: clab-basic-h2
interfaces:
- bridge: basic_6
  gateway:
    ipv4: 172.16.1.4/24
  ifindex: 1
  ifname: eth1
  ipv4: 172.16.1.6/24
  linkindex: 6
  mtu: 1500
  name: h2 -> [l2]
  neighbors:
  - ifname: Ethernet3
    ipv4: 172.16.1.4/24
    node: l2
  role: stub
  type: lan
mgmt:
  ifname: eth0
  ipv4: 192.168.121.106
  mac: 08-4F-A9-00-00-06
mtu: 1500
role: host
