# Ansible inventory created from ['bgp.yml', 'package:topology-defaults.yml']
#
---
ansible_become: true
ansible_become_method: enable
ansible_connection: network_cli
ansible_network_os: eos
ansible_ssh_pass: admin
ansible_user: admin
