# Ansible inventory created from ['bgp.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
box: python:3.9-alpine
clab:
  kind: linux
hostname: clab-basic-h1
interfaces:
- bridge: basic_5
  gateway:
    ipv4: 172.16.0.3/24
  ifindex: 1
  ifname: eth1
  ipv4: 172.16.0.5/24
  linkindex: 5
  mtu: 1500
  name: h1 -> [l1]
  neighbors:
  - ifname: Ethernet3
    ipv4: 172.16.0.3/24
    node: l1
  role: stub
  type: lan
mgmt:
  ifname: eth0
  ipv4: 192.168.121.105
  mac: 08-4F-A9-00-00-05
mtu: 1500
role: host
